development:
  secret_key_base: 118603d38fd1c95089ca37e288ccc8890765135d42867b94b1708568ee74f79148baa769b281571e3603c21017d17c6188b296d7361fd7c4d5e73b4527d7600d
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
